version: '3'

services:
  web:
    image: wordpress
    ports:
      - "8086:80"
    environment:
      - WORDPRESS_DB_PASSWORD=Pa$$w0rd
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=Pa$$w0rd
      - MYSQL_DATABASE=wordpress
